### ISSUE TITLE
Not working on real hardware

### ISSUE THREAD

**Issue by vladkorotnev** [samyuu/TotallyLegitArcadeController#3]
Configuration:
All patches except for touch slider applied. Input emulator and touch slider emulator are disabled in components.ini. Player data manager is enabled. 

Expected result: 
Application works just as fine on real system. 

Actual result:
Controls don't work except for the touch slider and mouse.

**Comment by samyuu** [comment]
This is caused by TLAC hooking the JVS update routine and not calling the original function afterwards.
For non NU hardware this is intended and convenient as we can then easily write to the input state ourselves.
Because installing the hook with the current method takes quite a bit of space I would rather not change the target address. An easy fix should be to manually call this function from within the hook if the input emulator component has been disabled. 
I will be doing some testing shortly.

**Comment by vladkorotnev** [comment]
Can it be just changed to not install the JVS update routine decided by a setting in config? Since JVS doesn't affect the RFID/Touchscreen/other emulated parts, it shouldn't degrade things much. Or is it used as some reference timer internally?

I just thought that disabling all the input components in the config wouldn't overwrite the JVS update routine, so it was a bit of a surprise it didn't.

**Comment by samyuu** [comment]
The jmp-PollInput function offered itself as an easy function to hook because of the large amount of alignment padding following it, though this is admittedly a bit of an oversight.
I have addressed this issue in 5ca4476 so it should now be resolve if the InputEmulator component is disabled.

**Comment by vladkorotnev** [comment]
Rolling a special property on the manager object just for that sounds a bit hacky... I'd probably go with some kind of a "BypassInputComponent" to replace the InputComponent maybe :-)

(No offense intended, it's still much better code quality than my [loader](https://github.com/vladkorotnev/gjmemyakaldr). Kudos for good design for such a specific kind of software!)

I'll test today's evening and report back how it works. Thanks for your support!

**Comment by vladkorotnev** [comment]
It's a bit fiddly and weird with Fast Loader on (first the menu appears and only in a few seconds the controller begins to work), but seems to work fine. Thanks! Closing.
